using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WpfApp39
{
    public class Word
    {
        public string word { get; set; }
        public string hint { get; set; }
    }
    public class WordCollections
    {
        public List<Word> Words { get; set; }
    }

    public class WordsList
    {
        public WordCollections wordCollections, wordCollectionsHard, wordCollectionsXtreme;

        public WordsList()
        {
            wordCollections = new WordCollections
            {

                Words = new List<Word>(){
               new  Word { word = "apple", hint = "A common fruit, often associated with technology." },
               new  Word { word = "giraffe", hint = "The tallest land animal." },
               new  Word { word = "python", hint = "A programming language and a large snake." },
               new  Word { word = "ocean", hint = "A large body of salt water." },
               new  Word { word = "mountain", hint = "A natural elevation of the earth’s surface." },
               new  Word { word = "puzzle", hint = "A game or problem that tests ingenuity." },
               new  Word { word = "keyboard", hint = "A primary input device for computers." },
               new  Word { word = "elephant", hint = "A large mammal with tusks and a trunk." },
               new  Word { word = "island", hint = "Land surrounded by water." },
               new  Word { word = "guitar", hint = "A musical instrument with strings." },
               new  Word { word = "diamond", hint = "A precious stone often used in jewelry." },
               new  Word { word = "notebook", hint = "Used for writing or drawing; also a type of computer." },
               new  Word { word = "satellite", hint = "An artificial object placed in orbit around a planet." },
               new  Word { word = "volcano", hint = "A mountain that can erupt with lava." },
               new  Word { word = "calendar", hint = "A system of organizing days for social, religious, or commercial purposes." },
               new  Word { word = "umbrella", hint = "Used to protect oneself from rain or sun." },
               new  Word { word = "parachute", hint = "Used to slow a descent through the air." },
               new  Word { word = "library", hint = "A place where books are kept." },
               new  Word { word = "stadium", hint = "A large venue for sports and events." },
               new  Word { word = "whistle", hint = "A small instrument that makes a sound when blown." },
               new  Word { word = "currency", hint = "A system of money used in a country." },
               new  Word { word = "pyramid", hint = "A monumental structure found in Egypt." },
               new  Word { word = "horizon", hint = "The line where the sky appears to meet the earth." },
               new  Word { word = "telescope", hint = "An instrument used to observe distant objects." },
               new  Word { word = "galaxy", hint = "A large system of stars and planets." },
               new  Word { word = "asteroid", hint = "A small rocky body orbiting the sun." },
               new  Word { word = "festival", hint = "A celebration, often with music, food, and performances." },
               new  Word { word = "fireplace", hint = "A structure used for heating a room by burning wood." },
               new  Word { word = "rainbow", hint = "A colorful arc seen after rain." },
               new  Word { word = "microphone", hint = "A device used to amplify or record sound." },
               new  Word { word = "bicycle", hint = "A two-wheeled vehicle powered by pedaling." },
               new  Word { word = "journal", hint = "A record of daily experiences or thoughts." },
               new  Word { word = "airplane", hint = "A powered flying vehicle with wings." },
               new  Word { word = "computer", hint = "A device used for processing information." },
               new  Word { word = "chocolate", hint = "A sweet food made from cacao beans." },
               new  Word { word = "sandwich", hint = "Two slices of bread with a filling between them." },
               new  Word { word = "backpack", hint = "A bag worn on the back, often used by students." },
               new  Word { word = "eleven", hint = "The number after ten." },
               new  Word { word = "kangaroo", hint = "A marsupial that hops and carries its young in a pouch." },
               new  Word { word = "photograph", hint = "A picture taken with a camera." },
               new  Word { word = "astronomy", hint = "The study of celestial objects and space." },
               new  Word { word = "electric", hint = "Related to the flow of charged particles." },
               new  Word { word = "submarine", hint = "A watercraft capable of underwater operation." },
               new  Word { word = "passport", hint = "An official document for international travel." },
               new  Word { word = "volleyball", hint = "A sport played by hitting a ball over a net." },
               new  Word { word = "magazine", hint = "A publication containing articles and illustrations." },
               new  Word { word = "language", hint = "A system of communication used by a particular community." },
               new  Word { word = "symphony", hint = "An elaborate musical composition for full orchestra." },
               new  Word { word = "diameter", hint = "A straight line passing through the center of a circle." },
               new  Word { word = "robot", hint = "A machine capable of carrying out complex tasks." },
               new  Word { word = "sunflower", hint = "A tall plant with a large yellow flower." },
               new  Word { word = "waterfall", hint = "A flow of water over a cliff." },
               new  Word { word = "dolphin", hint = "A highly intelligent marine mammal." },
               new  Word { word = "puzzle", hint = "A game or problem that tests ingenuity." },
               new  Word { word = "airplane", hint = "A powered flying vehicle with wings." },
               new  Word { word = "octopus", hint = "A sea creature with eight arms." },
               new  Word { word = "trophy", hint = "An award given for a victory or achievement." },
               new  Word { word = "skyscraper", hint = "A very tall building." },
               new  Word { word = "giraffe", hint = "The tallest land animal." },
               new  Word { word = "basketball", hint = "A sport played by throwing a ball into a hoop." },
               new  Word { word = "sculpture", hint = "A three-dimensional work of art." },
               new  Word { word = "chandelier", hint = "A decorative light fixture that hangs from the ceiling." },
               new  Word { word = "mirror", hint = "A reflective surface that shows images." },
               new  Word { word = "helicopter", hint = "A flying vehicle with rotating blades." },
               new  Word { word = "comet", hint = "A small celestial body that orbits the sun." },
               new  Word { word = "sandcastle", hint = "A sculpture made from sand, often built on a beach." },
               new  Word { word = "globe", hint = "A spherical model of Earth." },
               new  Word { word = "windmill", hint = "A structure that converts wind energy into power." },
               new  Word { word = "trampoline", hint = "A device for jumping, consisting of a taut fabric surface." },
               new  Word { word = "jungle", hint = "A dense, tropical forest." },
               new  Word { word = "statue", hint = "A carved or molded figure." },
               new  Word { word = "whale", hint = "A large marine mammal." },
               new  Word { word = "tornado", hint = "A violent rotating column of air." },
               new  Word { word = "squirrel", hint = "A small rodent with a bushy tail." },
               new  Word { word = "plasma", hint = "A state of matter distinct from solids, liquids, and gases." },
               new  Word { word = "snowman", hint = "A figure made of snow, often decorated with a hat and scarf." },
               new  Word { word = "ladder", hint = "A tool used to climb up or down." },
               new  Word { word = "skateboard", hint = "A board with wheels used for riding and performing tricks." },
               new  Word { word = "medal", hint = "A small piece of metal awarded for achievement." },
               new  Word { word = "penguin", hint = "A flightless bird that lives in the Southern Hemisphere." },
               new  Word { word = "sunset", hint = "The daily disappearance of the sun below the horizon." },
               new  Word { word = "campfire", hint = "A fire used for cooking and warmth while camping." },
               new  Word { word = "notebook", hint = "Used for writing or drawing; also a type of computer." },
               new  Word { word = "dinosaur", hint = "A prehistoric reptile." },
               new  Word { word = "balloon", hint = "A flexible bag filled with gas, used for decoration or flying." },
               new  Word { word = "puzzle", hint = "A game or problem that tests ingenuity." },
               new  Word { word = "acorn", hint = "The nut of an oak tree." },
               new  Word { word = "hotairballoon", hint = "A balloon that is lifted by heating the air inside." },
               new  Word { word = "marathon", hint = "A long-distance running race." },
               new  Word { word = "washboard", hint = "A tool used for washing clothes by hand." },
               new  Word { word = "geode", hint = "A rock containing crystals or mineral deposits inside." },
               new  Word { word = "lantern", hint = "A portable light source." },
               new  Word { word = "dragonfly", hint = "An insect with large, transparent wings." },
               new  Word { word = "carousel", hint = "A rotating amusement ride with animals to ride on." },
               new  Word { word = "sundae", hint = "A dessert made with ice cream and toppings." },
               new  Word { word = "grapefruit", hint = "A large citrus fruit with a tangy flavor." },
               new  Word { word = "jigsaw", hint = "A type of puzzle consisting of interlocking pieces." },
               new  Word { word = "zeppelin", hint = "A large airship used for travel." },
               new  Word { word = "telescope", hint = "An instrument used to observe distant objects." },
               new  Word { word = "fountain", hint = "A structure that shoots water into the air." },
               new  Word { word = "vortex", hint = "A spinning, whirlpool-like motion of fluids." },
               new  Word { word = "icicle", hint = "A hanging piece of ice formed by dripping water." },
               new  Word { word = "quicksand", hint = "A wet, sandy ground that traps objects." }

                }

            };

            wordCollectionsHard = new WordCollections
            {
                Words = new List<Word>
                {
                    new Word { word = "hippopotamus", hint = "A large mammal native to sub-Saharan Africa." },
                    new  Word { word = "xenophobia", hint = "Fear or hatred of strangers or foreigners." },
                    new   Word { word = "exhilaration", hint = "Feeling of extreme excitement or happiness." },
                    new   Word { word = "misanthropic", hint = "Disliking or avoiding human society." },
                    new   Word { word = "quintessential", hint = "Representing the most perfect or typical example of something." },
                    new   Word { word = "subterranean", hint = "Existing or occurring beneath the earth's surface." },
                    new   Word { word = "uncharacteristic", hint = "Not typical of a particular person or thing." },
                    new   Word { word = "sesquipedalian", hint = "Characterized by long words; long-winded." },
                    new   Word { word = "ambidextrous", hint = "Able to use both hands equally well." },
                    new   Word { word = "circumlocution", hint = "The use of many words where fewer would suffice." },
                    new   Word { word = "idiosyncratic", hint = "Peculiar or individual in behavior or thought." },
                    new   Word { word = "labyrinthine", hint = "Like a labyrinth; irregular and twisting." },
                    new   Word { word = "magnanimously", hint = "In a generous or forgiving manner." },
                    new   Word { word = "inconspicuous", hint = "Not easily noticeable." },
                    new   Word { word = "anachronistic", hint = "Belonging to a period other than that being portrayed." },
                    new   Word { word = "indefatigable", hint = "Persisting tirelessly." },
                    new   Word { word = "ostentatiously", hint = "In a showy or exaggerated way." },
                    new   Word { word = "multifarious", hint = "Many and of various types." },
                    new   Word { word = "perspicacious", hint = "Having a ready insight into things; shrewd." },
                    new   Word { word = "insurmountable", hint = "Too great to be overcome." },
                    new   Word { word = "discombobulate", hint = "To confuse or disconcert." },
                    new   Word { word = "flabbergasted", hint = "Extremely surprised or shocked." },
                    new   Word { word = "subconscious", hint = "Concerning the part of the mind not fully aware but influencing actions." },
                    new   Word { word = "philanthropic", hint = "Seeking to promote the welfare of others." },
                    new   Word { word = "schadenfreude", hint = "Pleasure derived from another's misfortune." },
                    new   Word { word = "melancholy", hint = "A feeling of pensive sadness." },
                    new   Word { word = "cryptocurrency", hint = "Digital or virtual currency that uses cryptography for security." },
                    new   Word { word = "prestidigitation", hint = "Magic tricks performed as entertainment." },
                    new   Word { word = "indispensable", hint = "Absolutely necessary." },
                    new   Word { word = "unbelievable", hint = "Impossible or very difficult to believe." },
                    new   Word { word = "euphoniously", hint = "In a pleasing or harmonious way." },
                    new   Word { word = "extraordinary", hint = "Very unusual or remarkable." },
                    new   Word { word = "incommunicado", hint = "Not able to communicate with others." },
                    new   Word { word = "obfuscation", hint = "The action of making something obscure, unclear, or unintelligible." },
                    new   Word { word = "jurisdiction", hint = "The official power to make legal decisions." },
                    new   Word { word = "superfluous", hint = "Unnecessary, especially through being more than enough." },
                    new   Word { word = "disingenuous", hint = "Not candid or sincere." },
                    new   Word { word = "unintelligible", hint = "Impossible to understand." },
                    new   Word { word = "circumspection", hint = "Cautious consideration of all circumstances and consequences." },
                    new   Word { word = "unquestionable", hint = "Not able to be disputed." },
                    new   Word { word = "subterfuge", hint = "Deceit used to achieve one's goal." },
                    new   Word { word = "revolutionary", hint = "Involving or causing a complete or dramatic change." },
                    new   Word { word = "unprecedented", hint = "Never done or known before." },
                    new   Word { word = "indescribable", hint = "Too unusual or extreme to be described." },
                    new   Word { word = "hallucinatory", hint = "Characterized by or involving hallucinations." },
                    new   Word { word = "thunderstruck", hint = "Extremely surprised or shocked." },
                    new   Word { word = "miscommunication", hint = "Failure to communicate adequately." },
                    new   Word { word = "extraordinaire", hint = "Outstanding or remarkable in a particular capacity." },
                    new   Word { word = "incontrovertible", hint = "Not able to be denied or disputed." },
                    new   Word { word = "incomprehensible", hint = "Impossible to understand or grasp." },
                    new   Word { word = "disenfranchised", hint = "Deprived of power or rights, especially the right to vote." },
                    new   Word { word = "transcendental", hint = "Relating to a spiritual or non-physical realm." },
                    new   Word { word = "prestidigitator", hint = "A person skilled in magic or sleight of hand." },
                    new   Word { word = "inconsequential", hint = "Not important or significant." },
                    new   Word { word = "bureaucratization", hint = "The process of becoming a complex administrative system." },
                    new   Word { word = "photosynthesis", hint = "The process by which plants use sunlight to synthesize food." },
                    new   Word { word = "impecuniosity", hint = "The state of having little or no money." },
                    new   Word { word = "indubitably", hint = "Impossible to doubt; unquestionable." },
                    new   Word { word = "philosophical", hint = "Relating to the study of fundamental nature of knowledge and existence." },
                    new   Word { word = "misinterpretation", hint = "The act of misunderstanding something." },
                    new   Word { word = "unobjectionable", hint = "Not likely to cause any objections or disagreements." },
                    new   Word { word = "cryptanalysis", hint = "The study of analyzing and breaking codes." },
                    new   Word { word = "disenchantment", hint = "Feeling of disappointment or disillusionment." },
                    new   Word { word = "counterintuitive", hint = "Contrary to what one would intuitively expect." },
                    new   Word { word = "circumference", hint = "The boundary line of a circle." },
                    new   Word { word = "superstitious", hint = "Belief in supernatural causes without rational basis." },
                    new   Word { word = "juxtaposition", hint = "The fact of two things being seen or placed close together with contrasting effect." },
                    new   Word { word = "irrefutable", hint = "Impossible to deny or disprove." },
                    new   Word { word = "concatenation", hint = "A series of interconnected things or events." },
                    new   Word { word = "discombobulated", hint = "Confused and disoriented." },
                    new   Word { word = "magnanimity", hint = "Generosity or nobility of spirit." },
                    new   Word { word = "unconventional", hint = "Not based on or conforming to what is generally done or believed." },
                    new   Word { word = "phenomenology", hint = "The study of structures of consciousness as experienced from a first-person perspective." },
                    new   Word { word = "overcompensate", hint = "To make excessive efforts to make up for a deficiency." },
                    new   Word { word = "unquestionably", hint = "Beyond doubt or dispute." },
                    new   Word { word = "counterproductive", hint = "Having the opposite effect to the one intended." },
                    new   Word { word = "posthumously", hint = "Occurring after a person’s death." },
                    new   Word { word = "supercalifragilistic", hint = "Extremely wonderful or impressive (fictional word)." },
                    new   Word { word = "counterbalance", hint = "A weight that balances another weight." },
                    new   Word { word = "overabundance", hint = "An excessive amount of something." },
                    new   Word { word = "inexplicable", hint = "Impossible to explain or understand." },
                    new   Word { word = "repercussions", hint = "Unintended consequences of an action." },
                    new   Word { word = "amphibious", hint = "Capable of living both on land and in water." },
                    new   Word { word = "pseudoscience", hint = "A system of beliefs mistakenly regarded as being based on the scientific method." },
                    new   Word { word = "imperceptible", hint = "So slight that it is not perceived." },
                    new   Word { word = "metamorphosis", hint = "A complete change in form or nature." },
                    new   Word { word = "hypothetically", hint = "Based on or serving as a hypothesis." },
                    new   Word { word = "microcosm", hint = "A small system that is a miniature version of a larger system." },
                    new   Word { word = "unfathomable", hint = "Too difficult to understand or comprehend." },
                    new   Word { word = "quintessence", hint = "The most perfect or typical example of something." },
                    new   Word { word = "miscalculation", hint = "An error in judgment or calculation." },
                    new   Word { word = "hyperventilate", hint = "To breathe abnormally fast or deep." },
                    new   Word { word = "commensurate", hint = "Corresponding in size or degree; proportionate." },
                    new   Word { word = "entanglement", hint = "A complicated or compromising relationship or situation." },
                    new   Word { word = "uncomfortable", hint = "Causing discomfort or unease." },
                    new   Word { word = "confrontation", hint = "A hostile or argumentative meeting or situation." }


                }
            };

            wordCollectionsXtreme = new WordCollections
            {
                Words = new List<Word>
                {
                    new Word { word = "electroencephalogram", hint = "A test or record of brain activity." },
                    new  Word { word = "otorhinolaryngology", hint = "The study of diseases of the ear, nose, and throat." },
                    new  Word { word = "pneumonoultramicroscopicsilicovolcanoconiosis", hint = "A lung disease caused by inhaling very fine silicate or quartz dust." },
                    new  Word { word = "antidisestablishmentarianism", hint = "Opposition to the withdrawal of state support from an established church." },
                    new  Word { word = "floccinaucinihilipilification", hint = "The action or habit of estimating something as worthless." },
                    new  Word { word = "hippopotomonstrosesquipedaliophobia", hint = "The fear of long words." },
                    new  Word { word = "thyroparathyroidectomized", hint = "Having undergone surgery to remove the thyroid and parathyroid glands." },
                    new  Word { word = "psychophysiological", hint = "Relating to the interaction between mind and body." },
                    new  Word { word = "trichotillomania", hint = "A compulsive urge to pull out one's hair." },
                    new  Word { word = "incomprehensibilities", hint = "Things that are impossible to understand." },
                    new  Word { word = "uncharacteristically", hint = "In a manner not typical of a particular person or thing." },
                    new  Word { word = "pharmacogenetics", hint = "The study of how genes affect a person's response to drugs." },
                    new  Word { word = "prognostication", hint = "The action of foretelling or prophesying future events." },
                    new  Word { word = "disproportionately", hint = "In a way that is out of proportion to something else." },
                    new  Word { word = "interdisciplinary", hint = "Relating to more than one branch of knowledge." },
                    new  Word { word = "unconstitutionally", hint = "In a manner that violates the constitution." },
                    new  Word { word = "counterrevolutionary", hint = "Opposing a revolution or revolutionary ideas." },
                    new  Word { word = "misinterpretation", hint = "The act of misunderstanding something." },
                    new  Word { word = "contradistinction", hint = "The distinction made by contrasting two things." },
                    new  Word { word = "thermodynamically", hint = "In a way that relates to the science of the relations between heat and other forms of energy." },
                    new  Word { word = "immunohistochemistry", hint = "A technique for identifying cellular or tissue components by means of antigen-antibody interactions." },
                    new  Word { word = "miscommunication", hint = "Failure to communicate clearly." },
                    new  Word { word = "extraterrestrial", hint = "Originating or existing outside the Earth." },
                    new  Word { word = "unintelligibility", hint = "The state of being impossible to understand." },
                    new  Word { word = "indistinguishable", hint = "Impossible to distinguish or tell apart." },
                    new  Word { word = "hypersensitivity", hint = "An exaggerated response by the immune system to a stimulus." },
                    new  Word { word = "institutionalization", hint = "The process of embedding something within an organization or culture." },
                    new  Word { word = "substantiality", hint = "The quality of being substantial or of having a solid basis." },
                    new  Word { word = "epistemologically", hint = "Relating to the theory of knowledge." },
                    new  Word { word = "reindustrialization", hint = "The process of reviving industries that have gone into decline." },
                    new  Word { word = "unscrupulousness", hint = "The quality of having or showing no moral principles." },
                    new  Word { word = "characteristically", hint = "In a manner typical of a particular person or thing." },
                    new  Word { word = "overintellectualize", hint = "To explain something in a way that is too focused on complex ideas or concepts." },
                    new  Word { word = "overenthusiastically", hint = "In an excessively enthusiastic manner." },
                    new  Word { word = "unpronounceability", hint = "The quality of being difficult or impossible to pronounce." },
                    new  Word { word = "hypercholesterolemia", hint = "Having high levels of cholesterol in the blood." },
                    new  Word { word = "disestablishmentarian", hint = "A supporter of the disestablishment of the Church of England." },
                    new  Word { word = "psychopathologically", hint = "Relating to the study of mental disorders." },
                    new  Word { word = "immunocompromised", hint = "Having an impaired or weakened immune system." },
                    new  Word { word = "anthropomorphically", hint = "In a manner that attributes human characteristics to non-human entities." },
                    new  Word { word = "unquantifiability", hint = "The inability to be measured or quantified." },
                    new  Word { word = "microspectrophotometry", hint = "A technique for measuring the spectra of microscopic samples." },
                    new  Word { word = "unsatisfactoriness", hint = "The quality of being inadequate or unfulfilling." },
                    new  Word { word = "untranslatability", hint = "The quality of being impossible to translate accurately from one language to another." },
                    new  Word { word = "decontamination", hint = "The process of removing or neutralizing contaminants." },
                    new  Word { word = "hypothalamically", hint = "In a manner relating to the hypothalamus, a region of the brain." },
                    new  Word { word = "photoautotrophically", hint = "In a way that relates to organisms that synthesize their own food using light as a source of energy." },
                    new  Word { word = "psychoneuroimmunology", hint = "The study of the interaction between psychological processes and the nervous and immune systems." }

                }
            };
        }


    }

}
